theme: jekyll-theme-merlot
# rating flicks of mountains i found on unsplash....an unprofessional opinion
## Matterhorn, Switzerland
[https://images.unsplash.com/photo-1545161296-d9c2c241f2ad?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80]
Fabrice Villard @fabulu75
### 8/10
good lighting at peak, pleasant sky tones, would've liked more definition in the valley
## Mont Blanc, France
[https://images.unsplash.com/photo-1517021897933-0e0319cfbc28?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80]
Simon Fitall @simonfitall
### 9/10
great depth and layers, points off for less-than-perfect quality and unappealing clouds
[https://unsplash.com/]
